opensearchdescription-body.ftl: update to naturalLanguageCoordinates
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> naturalLanguageCode  [in template "opensearchdescription-body_en" at line 15, column 108]